/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlefinanceiro.apresentacao;

import controlefinanceiro.negocio.Despesa;
import controlefinanceiro.negocio.Integrante;
import controlefinanceiro.negocio.Receita;
import controlefinanceiro.persistencia.DespesaDAO;
import controlefinanceiro.persistencia.IntegranteDAO;
import controlefinanceiro.persistencia.PessoaDAO;
import controlefinanceiro.persistencia.ReceitaDAO;
import controlefinanceiro.suporte.ComboItem;
import controlefinanceiro.suporte.CombosDAO;
import controlefinanceiro.suporte.Formatacao;
import controlefinanceiro.suporte.JtextFieldSomenteNumeros;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor Martinez
 */
public class FrmGerenciaFinancas extends javax.swing.JFrame {

    double teste = 0;

    public FrmGerenciaFinancas() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);
        new CombosDAO().popularCombo("integrante", 3, jComboBox1,
                "WHERE pessoa_id = " + System.getProperty("Login"),
                new PessoaDAO().consultar(Integer.valueOf(System.getProperty("Login"))).getNome());
        new CombosDAO().popularCombo("tipo_despesa", 2, jComboBox2, "", "");
        new PessoaDAO().popularTabela(jTable1, jTextField3.getText());
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            teste += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 3)).replace("R$ ", "").replace(",", "."));
        }
        jTextField5.setText("R$ " + Formatacao.formatarDecimal(teste));
        teste = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new JtextFieldSomenteNumeros(7, true);
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Financeiro - Gerenciamento De Finanças");

        jLabel3.setText("Campo obrigatório");
        jLabel3.setVisible(false);
        jLabel3.setForeground(Color.RED);

        jButton4.setText("Adicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome já cadastrado");
        jLabel4.setVisible(false);
        jLabel4.setForeground(Color.RED);

        jLabel5.setText("* Tipo de despesa:");
        jLabel5.setVisible(false);

        jLabel6.setText("Campo obrigatório");
        jLabel6.setVisible(false);
        jLabel6.setForeground(Color.RED);

        jLabel7.setText("* Receita:");

        jLabel9.setText("Campo obrigatório");
        jLabel9.setVisible(false);
        jLabel9.setForeground(Color.RED);

        jLabel8.setText("* Valor:");

        jLabel10.setText("Campo obrigatório");
        jLabel10.setVisible(false);
        jLabel10.setForeground(Color.RED);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setVisible(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Receita");
        jRadioButton1.setSelected(true);
        jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButton1FocusGained(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Despesa");
        jRadioButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButton2FocusGained(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jLabel1.setText("* Pessoa:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBox2.setVisible(false);
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox2FocusLost(evt);
            }
        });

        jLabel2.setText("Tipo de finança:");

        jLabel11.setText("Cadastrar pessoa:");
        jLabel11.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel11))
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo (Subtipo)", "Local Aplicado", "Nome", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Buscar:");

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setText("R$ 00,00");

        jLabel13.setText("Saldo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusLost
        if (jComboBox2.getSelectedIndex() == 0) {
            jLabel6.setVisible(true);
        } else {
            jLabel6.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox2FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        if (jTextField4.getText().isEmpty()) {
            jLabel10.setVisible(true);
        } else {
            jLabel10.setVisible(false);
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (jTextField2.getText().isEmpty()) {
            jLabel9.setVisible(true);
        } else {
            jLabel9.setVisible(false);
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jRadioButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton2FocusGained
        jLabel7.setText("* Despesa:");
        jLabel5.setVisible(true);
        jComboBox2.setVisible(true);
    }//GEN-LAST:event_jRadioButton2FocusGained

    private void jRadioButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton1FocusGained
        jLabel7.setText("* Receita:");
        jLabel5.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox2.setSelectedIndex(0);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jRadioButton1FocusGained

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (jTextField1.getText().isEmpty()) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.isVisible()) {

            Integrante integrante = new Integrante();

            integrante.setId(0);
            integrante.setPessoaId(Integer.valueOf(System.getProperty("Login")));
            integrante.setNome(jTextField1.getText().toLowerCase());

            if (!new IntegranteDAO().verificar(jTextField1.getText().toLowerCase())
                    && new IntegranteDAO().salvar(integrante)) {
                jLabel11.setVisible(false);
                jTextField1.setVisible(false);
                jButton1.setText("+");
                jTextField1.setText("");
                jLabel4.setVisible(false);
                new CombosDAO().popularCombo("integrante", 3, jComboBox1,
                        "WHERE pessoa_id = " + System.getProperty("Login"),
                        new PessoaDAO().consultar(Integer.valueOf(System.getProperty("Login"))).getNome());
            } else {
                jLabel4.setVisible(true);
            }
        } else {
            jLabel11.setVisible(true);
            jTextField1.setVisible(true);
            jButton1.setText("Adicionar");
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        if (jComboBox1.getSelectedIndex() == 0) {
            jLabel3.setVisible(true);
        } else {
            jLabel3.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (jComboBox1.getSelectedIndex() != 0
                && (jRadioButton1.isSelected() || (jRadioButton2.isSelected() && jComboBox2.getSelectedIndex() != 0))
                && !jTextField2.getText().isEmpty()
                && !jTextField4.getText().isEmpty()) {
            if (jRadioButton1.isSelected()) {

                Receita receita = new Receita();

                receita.setId(0);
                if (jComboBox1.getSelectedIndex() == 1) {
                    receita.setPessoaId(Integer.valueOf(System.getProperty("Login")));
                    receita.setIntegranteId(null);
                } else {
                    receita.setPessoaId(null);
                    ComboItem cpes = (ComboItem) jComboBox1.getSelectedItem();
                    receita.setIntegranteId(cpes.getCodigo());
                }
                receita.setValor(Double.parseDouble(jTextField4.getText().replace(',', '.')));
                receita.setDescricao(jTextField2.getText());

                if (new ReceitaDAO().salvar(receita)) {

                    JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");

                    jLabel11.setVisible(false);
                    jTextField1.setVisible(false);
                    jTextField1.setText("");
                    jButton1.setText("+");
                    jLabel4.setVisible(false);
                    jRadioButton1.setSelected(true);
                    jLabel7.setText("* Receita:");
                    jTextField2.setText("");
                    jLabel5.setVisible(false);
                    jComboBox2.setVisible(false);
                    jComboBox2.setSelectedIndex(0);
                    jTextField4.setText("");
                    jComboBox1.requestFocus();
                    new PessoaDAO().popularTabela(jTable1, jTextField3.getText());

                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        teste += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 3)).replace("R$ ", "").replace(",", "."));
                    }
                    jTextField5.setText("R$ " + Formatacao.formatarDecimal(teste));
                    teste = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Problemas ao salvar o registro.");
                }
            } else {

                Despesa despesa = new Despesa();

                despesa.setId(0);
                if (jComboBox1.getSelectedIndex() == 1) {
                    despesa.setPessoaId(Integer.valueOf(System.getProperty("Login")));
                    despesa.setIntegranteId(null);
                } else {
                    despesa.setPessoaId(null);
                    ComboItem cpes = (ComboItem) jComboBox1.getSelectedItem();
                    despesa.setIntegranteId(cpes.getCodigo());
                }
                ComboItem cdes = (ComboItem) jComboBox2.getSelectedItem();
                despesa.setTipoDespesaId(cdes.getCodigo());
                despesa.setValor(Double.parseDouble(jTextField4.getText().replace(',', '.')));
                despesa.setDescricao(jTextField2.getText());

                if (new DespesaDAO().salvar(despesa)) {

                    JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");

                    jLabel11.setVisible(false);
                    jTextField1.setVisible(false);
                    jTextField1.setText("");
                    jButton1.setText("+");
                    jLabel4.setVisible(false);
                    jRadioButton1.setSelected(true);
                    jLabel7.setText("* Receita:");
                    jTextField2.setText("");
                    jLabel5.setVisible(false);
                    jComboBox2.setVisible(false);
                    jComboBox2.setSelectedIndex(0);
                    jTextField4.setText("");

                    new PessoaDAO().popularTabela(jTable1, jTextField3.getText());

                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        teste += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 3)).replace("R$ ", "").replace(",", "."));
                    }
                    jTextField5.setText("R$ " + Formatacao.formatarDecimal(teste));
                    teste = 0;

                } else {
                    JOptionPane.showMessageDialog(null, "Problemas ao salvar o registro.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new PessoaDAO().popularTabela(jTable1, jTextField3.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?", "Select an Option", 2) == JOptionPane.OK_OPTION) {
                if (jTable1.getValueAt(jTable1.getSelectedRow(), 0).equals("Receita")) {
                    new ReceitaDAO().excluir(Integer.parseInt((String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6)));
                    JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                    new PessoaDAO().popularTabela(jTable1, jTextField3.getText());
                } else {
                    new DespesaDAO().excluir(Integer.parseInt((String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6)));
                    JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                    new PessoaDAO().popularTabela(jTable1, jTextField3.getText());
                }
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    teste += Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 3)).replace("R$ ", "").replace(",", "."));
                }
                jTextField5.setText("R$ " + Formatacao.formatarDecimal(teste));
                teste = 0;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
